name: Change Item Display Name
version: 1.1.2
main: br.AtomGamers.cidn.Main
commands:
  itemname:
    description: Comando name.
    aliases: [changeitemname, itemn, iname, in]
  itemdesc:
    description: Comando desc.
    aliases: [changeitemdesc, itemd, idesc, id]
